spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 161730020752-sugnhgid62biu91ohlvnf9bncg0l81e4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
